id: P007980
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1PD181165
  title: སྔ་འགྱུར་གཡག་ཟེ་དགོན་གྱི་འདོན་ཆ་ལས། མདོས་དང་དབང་སྣ་ཚོགས་ཀྱི་སྐོར།
  author: ''
  volumes:
    c15ba9c309f74f99a814c547bd573e87:
      image_group_id: I1KG16324
      title: Volume 1 of snga 'gyur g.yag ze dgon gyi 'don cha las/[ ]mdos dang dbang
        sna tshogs kyi skor/
      volume_number: 1
      total_pages: 976
      base_file: v001.txt
