id: P007980
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD181165
  title: སྔ་འགྱུར་གཡག་ཟེ་དགོན་གྱི་འདོན་ཆ་ལས། མདོས་དང་དབང་སྣ་ཚོགས་ཀྱི་སྐོར།
  author: ''
  volumes:
    a944336fb248436591957d9c4844639f:
      image_group_id: I1KG16324
      title: ''
      volume_number: 1
      total_pages: 976
ebook_metadata:
  title: སྔ་འགྱུར་གཡག་ཟེ་དགོན་གྱི་འདོན་ཆ་ལས། མདོས་དང་དབང་སྣ་ཚོགས་ཀྱི་སྐོར།
  author: ''
  sku: P007980
  cover: cover.jpg
  layers:
  - pagination
