id: I16033933
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T10:09:09+00:00'
last_modified: '2022-06-09T08:15:41.722852+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD181165
  title: སྔ་འགྱུར་གཡག་ཟེ་དགོན་གྱི་འདོན་ཆ་ལས། མདོས་དང་དབང་སྣ་ཚོགས་ཀྱི་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4CEB:
      image_group_id: I1KG16324
      title: Volume 1 of snga 'gyur g.yag ze dgon gyi 'don cha las/[ ]mdos dang dbang
        sna tshogs kyi skor/
      total_pages: 976
      order: 1
      base_file: 4CEB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
